name: build

on:
  push: 
    branches: [main,develop]
  pull_request: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: build 
        run: src/cmd/main.go